# Site settings
title: InVesalius
email: invesalius@cti.gov.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "/Ion-Jekyll-Theme" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://invesalius.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  invesalius

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal

include: ["_images", "_sources", "_sphinx_design_static", "_static"]
exclude: ["edit_documentation_here", "documentation_preview"]